// PROTOTYPE — throwaway. Generates one thin launcher per catalog skill, so no
// skill hand-writes bootstrap. This is the DRY mechanism: 20 skills -> 20
// generated 4-line shims that all route to the one runtime-exec engine.
// Mirrors how the template already generates plugin.json from plugin.config.json.
import { readFileSync, writeFileSync, chmodSync, mkdirSync } from "node:fs"
import { join } from "node:path"

const here = import.meta.dir
const catalog = JSON.parse(readFileSync(join(here, "catalog.json"), "utf8")) as {
	skills: Record<string, { entry: string; runtimeProfile: string }>
}
const binDir = join(here, "bin")
mkdirSync(binDir, { recursive: true })

function launcher(skillId: string): string {
	return `#!/bin/sh
# GENERATED by runtime-custody/generate.ts — do not edit. Edit catalog.json + regenerate.
set -eu
d=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
exec "$d/runtime-exec.sh" run ${skillId} -- "$@"
`
}

const written: string[] = []
for (const skillId of Object.keys(catalog.skills)) {
	const path = join(binDir, skillId)
	writeFileSync(path, launcher(skillId))
	chmodSync(path, 0o755)
	written.push(`bin/${skillId}`)
}
if (process.argv.includes("--check")) {
	// drift check: regenerate in-memory and compare (mirrors generate:check)
	let drift = false
	for (const skillId of Object.keys(catalog.skills)) {
		const on = readFileSync(join(binDir, skillId), "utf8")
		if (on !== launcher(skillId)) { console.error(`drift: bin/${skillId}`); drift = true }
	}
	console.log(drift ? "DRIFT" : "launchers current")
	process.exit(drift ? 1 : 0)
}
console.log(JSON.stringify({ generated: written }))
